// Generated by make_divider.py

#ifndef ATM_DIV_TL_H
#define ATM_DIV_TL_H

#include <stdint.h>

// Divide by 1.4783411417664412
static /*inline*/ uint16_t div_tl(uint16_t n) {
    uint16_t q = (((uint32_t) 23126UL)*((uint32_t) n)) >> 16UL;
    uint16_t t = (((n - q) >> 1) + q) >> 0;
    return t;
}

#endif
